spring.application.name=recapbot
spring.h2.console.enabled=true
spring.profiles.active=local

spring.datasource.url=jdbc:h2:file:./data/recapbot
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=update


telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.baseUrl=https://api.telegram.org

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USER}
spring.data.redis.password=${REDIS_PASSWORD}


crypto.secret-key=${CRYPTO_SECRET_KEY}


#GEMINI LLM
gemini.api.key=${GEMINI_API_KEY}
gemini.api.model=gemini-3-flash-preview
#gemini.api.model=gemini-flash-latest
gemini.api.baseUrl=https://generativelanguage.googleapis.com/v1beta/models


#LOCAL LLM
local.cli-path=${LOCAL_BIN_PATH}
local.model-path=${LOCAL_MODEL_PATH}
local.language=it
local.ffmpeg-path=${FFMPEG_PATH}

#OPENAI LLM(?)
openai.api.key=x;
openai.api.model=y;
openai.api.baseUrl=z;